CREATE TABLE `BONUS` (
  `EMP_ID` int(11) NOT NULL,
  `PAYMENTS` int(11) DEFAULT NULL,
  PRIMARY KEY (`EMP_ID`)
);


CREATE TABLE `EMP` (
  `EMP_ID` int(11) NOT NULL,
  `EMP_NAME` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BASIC_SALARY` int(11) DEFAULT NULL,
  `GRADE_CODE` int(11) NOT NULL,
  PRIMARY KEY (`EMP_ID`)
);

CREATE TABLE `GRADE` (
  `GRADE_CODE` int(11) NOT NULL,
  `BONUS_MAGNIFICATION` int(11) DEFAULT NULL,
  `FIXED_BONUS` int(11) DEFAULT NULL,
  PRIMARY KEY (`GRADE_CODE`)
);
